---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  env:
    TZ: UTC
  pattern:
    - "./packages/**/__tests__/*.test.ts"
    - "./packages/**/__tests__/*.test.tsx"
postMerge:
  env:
    TZ: UTC
  pattern:
    - "./packages/**/__tests__/*.test.ts"
    - "./packages/**/__tests__/*.test.tsx"
postRun:
  command:
    - yarn --version
version: 1.0.0
