---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  env:
    TZ: UTC
  pattern:
    - "./packages/**/*.test{.ts,.tsx}"
postMerge:
  env:
    TZ: UTC
  pattern:
    - "./packages/**/*.test{.ts,.tsx}"
postRun:
  command:
    - yarn --version
version: 1.0
